### ISSUE TITLE
Test model eos7qga

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos7qga#2]
This model is ready for testing @karthikjetty and @pauline-banye !
thanks!

**Comment by paulinebanye** [comment]
@GemmaTuron 
### MODEL TEST FOR EOS7QGA

## CLI
- [x]  Model eos7qga fetched, served and ran successfully on the CLI.
- [X] Model was tested using a list of smiles and a single smile string
[eos7qga_fetch.log](https://github.com/ersilia-os/eos7qga/files/10558603/eos7qga_fetch.log)
[eos7qga_list_run.csv](https://github.com/ersilia-os/eos7qga/files/10558606/eos7qga_list_run.csv)
[eos7qga_run.csv](https://github.com/ersilia-os/eos7qga/files/10558638/eos7qga_run.csv)


## COLAB
- [x]  Model eos7qga fetched, served and ran successfully on colab
[eos7qga_output.csv](https://github.com/ersilia-os/eos7qga/files/10558747/eos7qga_output.csv)
https://colab.research.google.com/drive/19652qPSN1y_y1cPH0EVEEmE04R_mGjZy?usp=sharing

**Comment by karthikjetty** [comment]
Model successfuly fetched on CLI: [eos7qga.log](https://github.com/ersilia-os/eos7qga/files/10560065/eos7qga.log)

Model successfully fetched and run on colab: https://colab.research.google.com/drive/1Rc71jybWdClgK4FSsBwIAByJxWUXvAd1#scrollTo=ipckLYxPS3GY

**Comment by DhanshreeA** [comment]
I see I got unassigned, but I had tested it anyway, and can confirm it works both on CLI and Colab. :grin: 
[Colab](https://colab.research.google.com/drive/1jD2qTBAA3GUqD1-Iw5S_GuFmqC-pNjAN?usp=sharing)
CLI: [eos9c7k_output.csv](https://github.com/ersilia-os/eos7qga/files/10565664/eos9c7k_output.csv)

**Comment by GemmaTuron** [comment]
wonderful thanks all!
